py/server.py

this is the basic server we can use to serve routes. its completely blocking, so no requests can be answered in parallel but really this is just a poc. we'll be throwing this away for something else off the shelf like mongrel2, nginx, tornado or the like once we get around to it

sample python server

---

py/server.py
src/tyr/handler.cc
src/tyr/route_handler.cc
valhalla/tyr/handler.h

server and handlers now work with jsonp callbacks (which seems to be something leaflet is making using of at least)

handle jsonp

---

.gitignore
Makefile.am
py/server.py
src/tyr/route_handler.cc
test/handlers.cc
test/json.cc
valhalla/tyr/json.h

also added a test for json stuff

server doesnt need to encode to utf8 the data already is

---

src/tyr/route_handler.cc

depend on odin
@dnesbitt61 @kevinkreiser @gknisely

TripDirections_Maneuver_Type updates

---

src/tyr/route_handler.cc

Switched to use valhalla::odin::DirectionsBuilder.Build
Updated maneuver type mapping

Added cardinal_direction_string

---

py/server.py

now the server wont block when multiple people hit it at once. its still not great as it will  use a bunch more memory (since the cache of tiles isn't a shared resource) but whatever its good for now. was worried about this because we'll soon have a chef recipe to put this thing out there on the cloud

multithreaded server

---

src/tyr/route_handler.cc

i was seeing routes pass that shouldnt have and it was because of the filtering not being used in the service

need to use road filter for costing type during search

---

.gitignore
Makefile.am
configure.ac
py/tyr_simple_server.py

so after installing you can run it with:
python -m tyr_simple_server valhalla.json

automake installs simple server

---

src/tyr/route_handler.cc
test/handlers.cc

Pass in property tree for costing configuration

---

test/handlers.cc

@dgearhart @dnesbitt61 @kevinkreiser

updated test conf to Tertiary for cut off.

---

src/tyr/route_handler.cc

TODO - some config control of relaxation factors and number of passes allowed.

Add multi-pass (needed for Asia routes!).

---

test/handlers.cc

@kevinkreiser @dgearhart @dnesbitt61

updated call to enhancer.

---

py/tyr_simple_server.py
src/tyr/handler.cc
test/handlers.cc

http://localhost:8002/route?json={%22instructions%22:true,%22loc%22:%5B%2240.33572521013457%2C-76.40781462192535%22,%2240.33624452479345%2C-76.40600681304932%22%5D,%22costing_method%22:%22auto%22}&jsonp=callback
notice the method of costing is no longer part of the path have to change demo for this

make json requests

---

conf/valhalla.json
src/tyr/custom_route_handler.cc
src/tyr/route_handler.cc
test/handlers.cc
valhalla/tyr/custom_route_handler.h
valhalla/tyr/handler.h
valhalla/tyr/route_handler.h

Change to floating point (not int meters)

Add units to JSON request

---

src/tyr/custom_route_handler.cc

paired with @gknisely 
@dnesbitt61 @kevinkreiser

Updated location assignment

---

src/tyr/custom_route_handler.cc

updated json keys to use underscores
Changed StopType to Type under Location

serialize does not depend on TripPath anymore

---

py/tyr_simple_server.py

this will allow us to have an elb in front of the service to tell whether its up or not

need a status handler, dummy for now

---

src/tyr/custom_route_handler.cc

Updated rough to match docs

---

src/tyr/custom_route_handler.cc
src/tyr/route_handler.cc
valhalla/tyr/custom_route_handler.h

Added DirectionsOptions

---

src/tyr/custom_route_handler.cc
test/handlers.cc

Changed latitude to lat and longitude to lon

---

src/tyr/custom_route_handler.cc
valhalla/tyr/custom_route_handler.h

Updated to use the units from the directions options

Updated to use the leg summary information from the trip directions

---

src/tyr/custom_route_handler.cc
src/tyr/route_handler.cc

Use PathInfo to pass path from PathAlgorithm to TripPathBuilder

---

.gitmodules
src/tyr/service.cc

if you do:
`http://localhost:8002/route?json={%22locations%22:%5B{%22lat%22:40.383604,%22lon%22:%20%20-76.637650},{%22lat%22:40.402978,%22lon%22:%20-76.534996},{%22lat%22:40.477815,%22lon%22:%20-76.561282}%5D,%22costing%22:%22auto%22}`
you will get:
[
{
"trip": {
"status": 0,
"status_message": "Found route between points",
"legs": [
{
"shape": "{rv_lA~oudqCyRgYwr@emAapA{hBiMcQ}NuYkf@q{@}DaHyLgXgOgXwWmt@iRwv@iS}|Akj@}xEiGwc@aSkj@cK}TgOm^cPqg@eFyk@eJwvAqHwvAm@yLd@cFf@yCbAiB`BiBxByBlAkB\\{@N{ALgDiW_h@u^ku@mUuc@}Twc@gS{_@kFkLumAodCiMyWyLsZwN_^sQ_h@oH}Tq]kjAeT}r@o{A_bF}_@qpAwg@_fByQgm@wb@uvAsVgx@o^wkA{Uww@c[qfAuJa\\yRso@q\\afAo]}hAufBa~Fqf@ubBsVux@a|@wsCcQkk@g]{iAgc@sxAwIwXyL{`@gSoq@gIs[uE{UiGm_@aD{VwCm^iB_^}@o]MiWLq]dAen@fHghErG_bEbAoh@fDgjBzAk_A`B{_AhC}fB`HiqEnDkhBxAi`A`DgkBL_Id@q\\lFw~CpBmrA …

allow for multipoint

---

src/tyr/service.cc

Added ability to disable narrative production.

---

src/tyr/service.cc

-Added logging for logstash
-additional logging if elapsed time is > threshold
- added route_name to response

Api and logging updates

---

src/tyr/service.cc

Added verbal multi-cue flag

---

configure.ac
scripts/install_service_deps.sh
src/tyr/service.cc

locked prime_server version to 0.3.2 and added DNT check for long_requests

Do Not Track - Conditional Logging

---

src/tyr/service.cc

Output transit type

---

src/tyr/service.cc

Added language to the trip results

---

src/tyr/service.cc

Return travel mode string for each maneuver

---

src/tyr/service.cc

switch transit route to transit info

---

src/tyr/service.cc

move the functions to maps, add other strings, and provide defaults should there be missing stuff in the proto

slight refactor of modetype additions

---

src/tyr/service.cc

Added travel_type

---

src/tyr/service.cc

Fix for iterator bug when serializing the locations

---

src/tyr/service.cc

Output latitude and longitude for a transit stop

---

src/tyr/service.cc
valhalla/tyr/service.h

Changes to address these issues:
valhalla/valhalla#8
valhalla/valhalla#9

API Logging / Logstash Updates
